    server:
    port: 8092

spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:file:~/test2
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

permissao-service:
    url: https://user-info.herokuapp.com