server:
    port: 8052

spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:file:~/test2
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true





#server:
#    port: 8030
#
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/votacao?autoReconnect=true&useSSL=false
#        username: root
#        password: root
#
#    jpa:
#        properties:
#            hibernate:
#                format_sql: true
#        hibernate:
#            ddl-auto: update
#
#permissao-service:
#    url: https://user-info.herokuapp.com
