version: 2
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd central-erros && ./gradlew clean build install --refresh-dependencies
  test:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ./central-erros
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Run Spring Application
          command: ./gradlew bootRun -Drun.profiles=dev.
      - run:
          name: Generate code coverage report
          command:
            ./gradlew jacocoTestReport
      - store_test_results:
          path: central-erros/build/test-results/test
      - store_artifacts:
          path: central-erros/build/test-results/test
          when: always
      - store_artifacts:
          path: central-erros/build/reports/jacoco/test/html
          when: always
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build