version: 2
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Change application properties
          command: echo $SPRING | base64 --decode >> central-erros/src/main/resources/application.properties
      - run:
          name: Install dependencies
          command: cd central-erros && ./gradlew clean build --refresh-dependencies
  test:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: cd central-erros && ./gradlew test
      - run:
          name: Generate code coverage report
          command:
            cd central-erros && ./gradlew jacocoTestReport
      - run:
          name: Change application properties
          command: echo $SPRING | base64 --decode >> central-erros/src/main/resources/application.properties
      - store_test_results:
          path: central-erros/build/test-results/test
      - store_artifacts:
          path: central-erros/build/test-results/test
          when: always
      - store_artifacts:
          path: central-erros/build/reports/jacoco/test/html
          when: always
  deploy:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - run:
          name: Create jar
          command: cd central-erros && ./gradlew bootJar
      - run:
          name: Change application properties
          command: echo $SPRING | base64 --decode >> central-erros/src/main/resources/application.properties
      - run:
          name: Deploy Master to Heroku
          command: |
            git subtree push --prefix central-erros https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master



